window.PH = window.PH || {};

PH.data = {
  categories: [
    { id: 'web-app',        label: 'Web App',            icon: 'globe' },
    { id: 'ai-tool',        label: 'AI Tool',             icon: 'cpu' },
    { id: 'dev-tool',       label: 'Dev Tool',            icon: 'terminal' },
    { id: 'mobile-app',     label: 'Mobile App',          icon: 'smartphone' },
    { id: 'browser-ext',    label: 'Browser Extension',   icon: 'puzzle' },
    { id: 'api',            label: 'API / Backend',        icon: 'server' },
    { id: 'automation',     label: 'Automation',          icon: 'zap' },
    { id: 'data-science',   label: 'Data Science',        icon: 'bar-chart-2' },
    { id: 'game',           label: 'Game',                icon: 'gamepad-2' },
    { id: 'open-source',    label: 'Open Source Lib',     icon: 'package' },
  ],

  difficulties: [
    { id: 'beginner',     label: 'Beginner',     desc: '5–8 hours',   color: '#16a34a' },
    { id: 'intermediate', label: 'Intermediate', desc: '2–3 days',    color: '#2563eb' },
    { id: 'advanced',     label: 'Advanced',     desc: '1–2 weeks',   color: '#ea580c' },
  ],

  techStacks: [
    'React', 'Next.js', 'Vue', 'Svelte', 'Vanilla JS',
    'Node.js', 'Python', 'FastAPI', 'Django', 'Flask',
    'Go', 'Rust', 'TypeScript', 'Supabase', 'Firebase',
    'Tailwind CSS', 'PostgreSQL', 'MongoDB', 'OpenAI API', 'LangChain',
  ],

  trending: [
    {
      id: 'ai-agent',
      title: 'AI Code Review Agent',
      category: 'AI Tool',
      difficulty: 'Intermediate',
      description: 'An autonomous agent that reviews PRs, detects bugs, and suggests refactors using LLMs.',
      tags: ['AI', 'Automation', 'GitHub'],
      hot: true,
    },
    {
      id: 'browser-copilot',
      title: 'Browser AI Copilot',
      category: 'Browser Extension',
      difficulty: 'Advanced',
      description: 'A Chrome extension that reads any webpage and lets you chat with it using AI.',
      tags: ['AI', 'Browser', 'Extension'],
      hot: true,
    },
    {
      id: 'cli-scaffolder',
      title: 'Smart CLI Scaffolder',
      category: 'Dev Tool',
      difficulty: 'Intermediate',
      description: 'CLI tool that generates project scaffolding from a natural language description.',
      tags: ['CLI', 'Dev Tool', 'Automation'],
      hot: false,
    },
    {
      id: 'personal-api',
      title: 'Personal Analytics API',
      category: 'API / Backend',
      difficulty: 'Beginner',
      description: 'A self-hosted REST API that tracks your productivity, habits, and daily metrics.',
      tags: ['API', 'Analytics', 'Self-hosted'],
      hot: false,
    },
    {
      id: 'llm-playground',
      title: 'LLM Prompt Playground',
      category: 'Web App',
      difficulty: 'Beginner',
      description: 'Compare prompts across multiple LLM providers side by side in a clean interface.',
      tags: ['AI', 'Web App', 'Tools'],
      hot: true,
    },
    {
      id: 'workflow-automator',
      title: 'No-Code Workflow Automator',
      category: 'Automation',
      difficulty: 'Advanced',
      description: 'Drag-and-drop automation workflows that connect APIs, webhooks, and triggers.',
      tags: ['Automation', 'No-Code', 'Webhooks'],
      hot: false,
    },
    {
      id: 'data-pipeline',
      title: 'Real-time Data Pipeline',
      category: 'Data Science',
      difficulty: 'Advanced',
      description: 'Stream and visualize real-time data from multiple sources with a live dashboard.',
      tags: ['Data', 'Streaming', 'Dashboard'],
      hot: true,
    },
    {
      id: 'dev-notes',
      title: 'Developer Notes App',
      category: 'Dev Tool',
      difficulty: 'Beginner',
      description: 'A minimal, blazing-fast notes app for devs — code block support, tag system, offline-first.',
      tags: ['Dev Tool', 'Notes', 'Productivity'],
      hot: false,
    },
  ],
};
